site_name: Cromwell
pages:
- Things: 
  - Stuff: index.md
#  - Current state: README.md
  - Getting started: Getting Help.md
  - Requirements: Requirements.md
  - Building: Building.md
  - Installing: Installing.md
  - Command Line usage: Command Line Usage.md
  - Getting started with WDL: Getting Started with WDL.md
  - Configuring: Configuring Cromwell.md
  - Security: Security.md
  - Backends: Backends.md
#  - Runtime Attributes: 
#  - Logging:
#  - Workflow options:
#  - Labels:
#  - Call caching:
#  - Imports:
#  - Sub workflows:
#  - REST API: 
theme: readthedocs
